[project]
name = "tla"
version = "0.1.0"
description = "TileAttention kernels for efficient inference"
authors = [{ name="Your Name", email="you@example.com" }]
dependencies = ["torch", "triton"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
