[project]
name = "tileops"
version = "0.1.0"
description = "TileOPs kernels for efficient inference"
authors = [{ name="Your Name", email="you@example.com" }]
dependencies = [    
    "torch>=2.1.0",
    "numpy>=1.23.5",
    "einops>=0.6.0",
    "Cython",
    "tqdm>=4.62.3",
    "typing_extensions>=4.10.0",
    "cloudpickle",
    "ml_dtypes",
    "psutil",
    "flash-linear-attention",
    "tilelang",
    "yapf==0.40.2",
    "toml==0.10.2",
    "tomli==2.0.1",
    "ruff==0.6.5",
    "codespell==2.3.0",
    "clang-format==15.0.7"
]
requires-python = ">=3.8"
license = { text = "MIT" }

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.yapf]
based_on_style = "yapf"
column_limit = 100
indent_width = 4

[tool.codespell]
ignore-words-list = "nd, te, ist, LOD, offen, NotIn, HSA"
skip = [
    "build",
    "3rdparty",
    "dist",
    ".venv"
]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    # "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    # "I",
]
ignore = [
    # Module level import not at top of file
    "E402",
    # star imports
    "F405", "F403",
    # ambiguous name
    "E741",
    # line too long
    "E501",
    # key in dict.keys()
    "SIM118",
    # memory leaks
    "B019",
    # No such file or directory
    "E902",
]